### ISSUE TITLE
unable to run compute_pareto.py from run_directory

### ISSUE THREAD

**Issue by adelejjeh** [luinardi/hypermapper#10] opened 2020-09-09 13:51 UTC
When I try to run `compute_pareto.py` from the run_directory that is specified in the json, I get an error saying `"No such file or directory: 'scripts/schema.json'"`. Both `HYPERMAPPER_HOME` and `PYTHONPATHS` environment variables have been set properly.

**Comment by arturluis** [comment] 2020-09-09 20:14
Thanks for letting us know. I just pushed a fix for this to master, let me know if the issue persists.

**Comment by adelejjeh** [comment] 2020-09-10 15:23
This is still not behaving as expected. There is an `all_` being added to the beginning of the image name, so if I set the name (in the json) to be `folder/file.pdf` it changes it to `all_folder/file.pdf` which causes it to crash because the folder `all_folder` doesn't exist..

**Comment by arturluis** [comment] 2020-09-10 17:22
Hello Adel, I think I see what the issue is. I've just pushed a fix for this issue to master. Can you let me know if the issue persists?

**Closed** 2020-09-22 18:34 UTC
